jest.config.js
jest.setup.js
src/core/wallet/__tests__/wallet-factory.test.ts
src/navigation/__tests__/__snapshots__/utils.test.tsx.snap
src/navigation/__tests__/navigation.test.tsx
src/navigation/__tests__/utils.test.tsx
src/navigation/navigation.tsx
src/navigation/utils.tsx
src/styles/colors.ts

Bottom bar navigation improvements. Bottom bar should be changed later on to custom component in order to accomodate redux theming.

change bottom navigation, add icons and colors

---

src/core/i18n/translation/locales/en.ts
src/library/button/button.tsx
src/library/button/styles.ts
src/navigation/navigation.tsx
src/navigation/utils.tsx
src/redux/app/__tests__/actions.test.ts
src/redux/wallets/actions.ts
src/screens/recover-wallet/__tests__/__snapshots__/recover-wallet.test.tsx.snap
src/screens/recover-wallet/__tests__/recover-wallet.test.tsx
src/screens/recover-wallet/recover-wallet.tsx
src/screens/recover-wallet/styles.ts

recover wallet flow.
to be revisited with better screen space management on android

add recover wallet

---

android/app/build.gradle
index.js
ios/Podfile.lock
package-lock.json

android - it works on 2 emulators, ios - cannot reproduce it on dev mode

---

src/components/skeleton-row/skeleton-row.tsx
src/components/skeleton-row/styles.ts
src/core/i18n/translation/locales/en.ts
src/navigation/navigation.tsx
src/screens/rewards/rewards.tsx
src/screens/rewards/styles.ts
src/styles/dimensions.ts

Rewards screen UI

---

android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/styles.xml
android/gradle.properties
src/app.tsx
src/navigation/__tests__/__snapshots__/navigation.test.tsx.snap
src/navigation/navigation.tsx

Android StatusBar, app background

---

src/core/blockchain/near/client.ts
src/core/blockchain/near/config.ts
src/redux/wallets/actions.ts
src/screens/send/components/fee-total/fee-total.tsx

Near: send screen all balance button not working properly

---

src/components/bottom-sheet/accounts-bottom-sheet/accounts-bottom-sheet.tsx
src/components/password-modal/components/password-pin/password-pin.tsx
src/components/password-modal/components/password-pin/styles.ts
src/core/i18n/translation/locales/en.ts
src/screens/manage-account/manage-account.tsx

- Accounts bottom sheet close on selection #320
- PIN Login hide fingerprint icon when touch id is not active #324
- Manage account screen: user shouldn't be able to deactivate a native token #329

Bug fixing

---

src/core/utils/remote-feature-config.ts
src/core/utils/remote-feature-config.web.ts
src/screens/create-wallet-confirm-mnemonic/create-wallet-confirm-mnemonic.tsx
src/screens/onboarding/onboarding.tsx

Remote Config

---

src/components/token-card/token-card.tsx
src/core/utils/fast-image.ts
src/core/utils/fast-image.web.ts
src/screens/manage-account/manage-account.tsx
src/screens/manage-token/manage-token.tsx
src/screens/settings/blockchain-portfolio/blockchain-portfolio.tsx
src/screens/token/components/list-account/list-account.tsx
src/screens/token/token.tsx

- Crashed on lib `react-native-fast-image` because it was using `requireNativeComponent`

Fix extension build

---

src/components/loading-modal/loading-modal.tsx
src/components/loading-modal/styles.ts

Fix Loading Modal

---

src/app.tsx
src/core/wallet-connect/wallet-connect-web.web.ts
src/core/wallet-connect/wc-state-helper.ts
src/redux/preferences/__tests__/__snapshots__/reducer.test.ts.snap
src/redux/preferences/__tests__/reducer.test.ts
src/redux/preferences/actions.ts
src/redux/preferences/reducer.ts
src/redux/preferences/state.ts
src/screens/settings/settings.tsx

don't send selected account, selected blockchain, selected wallet
send user preferences
added device id to state

modify state sent to extension

---

src/components/legal/legal-modal/legal-modal.tsx
src/screens/token/token.tsx

- legal modal change routeName for display
- fix crash on Token screen

Fix Legal Modal

---

src/screens/create-wallet-confirm-mnemonic/__tests__/__snapshots__/create-wallet-confirm-mnemonic.test.tsx.snap
src/screens/create-wallet-confirm-mnemonic/create-wallet-confirm-mnemonic.tsx
src/screens/create-wallet-confirm-mnemonic/styles.ts

Create wallet confirm mnemonic label

---

src/components/amount/amount.tsx
src/components/token-dashboard/__tests__/__snapshots__/token-dashboard.test.tsx.snap
src/components/token-dashboard/styles.ts
src/components/token-dashboard/token-dashboard.tsx
src/library/text/__tests__/__snapshots__/text.test.tsx.snap
src/library/text/text.tsx
src/screens/dashboard/dashboard.tsx
src/screens/dashboard/styles.ts
src/screens/manage-token/styles.ts

TODO: animate list cards top padding 
Demo Video 1: https://drive.google.com/open?id=18Xstw_cS6v04GAQfzTnQ1RmPIgAGYNSh
Demo Video 2: https://drive.google.com/open?id=17UwUJvhiassjo2QXBSCWxogmup9DvE-N

Dashboard scroll entire page

---

android/app/src/beta/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
extension/webpack.config.js
package-lock.json
package.json
src/components/account-create/styles.ts
src/screens/manage-token/styles.ts
src/screens/send/__tests__/__snapshots__/send.test.tsx.snap
src/screens/send/components/add-address/styles.ts
src/screens/send/components/enter-amount/styles.ts
src/screens/send/components/extra-fields/memo/memo.tsx
src/screens/send/components/extra-fields/memo/styles.ts
src/screens/send/components/gas-fee-advanced/gas-fee-advanced.tsx
src/screens/send/components/gas-fee-advanced/styles.ts
src/screens/send/send.tsx
src/screens/send/styles.ts

- fix also keyboard over text input

 Send Screen Scrollable

---

src/components/password-modal/password-modal-component.tsx
src/redux/wallets/actions.ts
src/screens/connect-hardware-wallet/connect-hardware-wallet.tsx
src/screens/connect-hardware-wallet/ledger-connect/ledger-connect.tsx
src/screens/create-wallet-confirm-mnemonic/create-wallet-confirm-mnemonic.tsx
src/screens/recover-wallet/recover-wallet.tsx

- on create/recover/connect flow, if you already have a PIN setup, don't create another one, request the current PIN
- also clear keychain storage when the last wallet has been deleted
- fix crashing bottom sheet on connect flow

Fix Create Password Flow

---

src/components/dialog/dialog-component.tsx
src/components/password-modal/password-modal-component.tsx
src/redux/contacts/actions.ts
src/screens/send/components/add-address/add-address.tsx
src/screens/send/components/address-book/address-book.tsx

#594 Account names are not saved in address book
Reorganised Dialog Component

Fix Dialog Deferred

---

src/screens/token/components/account-settings/account-settings.tsx
src/screens/token/components/account-settings/styles.ts

Fix Account Settings

---

src/screens/dashboard/dashboard.tsx

- android was crashing on start

Fix Android Build

---

src/components/keyboard-custom/styles.ts
src/screens/send/send.tsx
src/screens/send/styles.ts

- Bottom nav on Send flow is below the fold. It should be visible all the time

Send Screen - Sticky bottom navigation

---

src/core/i18n/translation/locales/en.ts
src/screens/settings/__tests__/__snapshots__/settings.test.tsx.snap

- `Terms & Conditions` should be replaced with `Terms of Service`

Fix Terms of Service spelling

---

src/redux/wallets/selectors.ts
src/screens/transactions-history/transactions-history.tsx

Fixed Issues: 
- #688 Transaction status on Transaction History page doesn't update
- #689 On Transaction History I'm able to see testnet transactions even if I'm on mainnet

Fix Transaction History

---

src/core/blockchain/ethereum/transaction.ts
src/core/blockchain/zilliqa/client-utils.ts
src/core/messaging/notifications/notifications.ts
src/core/utils/balance.ts
src/core/utils/format-number.ts
src/redux/wallets/reducer.ts
src/redux/wallets/selectors.ts
src/screens/recover-wallet/recover-wallet.tsx

I did not test all the fixes, we should test them before merging ....

Fix sentry errors

---

ios/fastlane/metadata/en-US/release_notes.txt
package.json
src/screens/transaction-request/extension-tx-request/extension-tx-request.tsx
src/screens/transaction-request/qr-code-tx-request/qr-code-tx-request.tsx

Also fix:
- `sendingToken` on `FeeOptions` (Tx Request Screen)
- Fix Extension Tx Request - XSGD

Release 1.4.3

---

src/components/bottom-sheet/accounts-bottom-sheet/accounts-bottom-sheet.tsx
src/screens/manage-accounts/manage-accounts.tsx

- also added swipeable on manage accounts

[NEAR] Do not delete account on index 0

---

src/redux/wallets/actions/pos-actions.ts

[NEAR] Delay pos Transaction for 2 seconds

---

src/components/account-summary/account-summary.tsx
src/components/token-card/token-card.tsx
src/core/blockchain/zilliqa/config.ts
src/core/blockchain/zilliqa/tokens/gzil.ts

[ZIL] gZIL decimals #1134

---

src/components/draggable-card-with-check-box/draggable-card-with-check-box.tsx
src/screens/dashboard/dashboard.tsx
src/screens/manage-accounts/manage-accounts.tsx

- remove accounts bottom sheet

Update manage accounts

---

src/components/widgets/render-module.tsx

Change from View to React Fragment

Update render module

---

src/core/i18n/translation/locales/en.ts
src/screens/transaction-details/transaction-details.tsx

- sol tx details - remove noce

SOL Updates

---

src/components/token-card/token-card.tsx
src/core/blockchain/solana/account.ts
src/core/i18n/translation/locales/en.ts
src/redux/utils/__tests__/__snapshots__/persistConfig.test.ts.snap
src/redux/utils/migrations/011.ts
src/redux/utils/migrations/index.ts
src/redux/utils/persistConfig.ts
src/redux/wallets/actions/pos-actions.ts
src/redux/wallets/actions/wallet-actions.ts
src/screens/manage-accounts/manage-accounts.tsx
src/screens/pos-actions/process-transactions/process-transactions.tsx
src/screens/send/components/add-address/add-address.tsx
src/screens/settings/set-currency/set-currency.tsx
src/screens/settings/set-currency/styles.ts
src/screens/token/token.tsx

- QR Code ZIL - update address, remove `zilliqa://`
- Select Currency Screen add ScrollView

SOL Update root account name

---

ios/fastlane/metadata/en-US/release_notes.txt
src/screens/transaction-details/transaction-details.tsx

Tx details - enable fees field

---

src/core/utils/balance.ts
src/screens/dashboard/dashboard.tsx
src/screens/settings/settings.tsx

Dashboard total balance

---

ios/fastlane/metadata/en-US/release_notes.txt
package.json
src/core/blockchain/solana/client.ts
src/core/blockchain/solana/transaction-utils.ts

- getCurrentBlockHash add commitment
- swap instructions

Solana fixes
